name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release --no-restore -o out
    - name: Upload generic artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: ${{ github.event.repository.name }}-generic
        path: out/generic 
    - name: Upload generic-netf artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: ${{ github.event.repository.name }}-generic-netf
        path: out/generic-netf
